# Generated by Django 4.1.2 on 2022-10-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_hotels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Hotel',
        ),
    ]
