# Generated by Django 4.1.2 on 2022-10-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_rename_hotels_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('touristArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.touristarea')),
            ],
        ),
    ]
