# Generated by Django 4.1.2 on 2022-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_busservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='busservice',
            name='fairFromDhaka',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='touristarea',
            name='distanceFromDhaka',
            field=models.IntegerField(default=0),
        ),
    ]
