# Generated by Django 4.1.2 on 2022-10-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_busservice_fairfromdhaka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='area_img'),
        ),
    ]
